// <auto-generated />
namespace MVC.Blog.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbinit));
        
        string IMigrationMetadata.Id
        {
            get { return "202005290906028_dbinit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
